apiVersion: v1
kind: Namespace
metadata:
  name: !{namespace}!
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: angular-deployment
  namespace: !{namespace}! 
spec: 
  selector: 
    matchLabels: 
      app: angular 
  replicas: 4 # tells deployment to run 2 pods matching the template 
  template:
    metadata: 
      labels: 
        app: angular 
    spec: 
      containers: 
      - name: angular 
        image: cdedevopsacr.azurecr.io/angularapp:latest
        #image: ramv1010/angularappdemo:latest
        ports: 
        - containerPort: 80
--- 
kind: Service 
apiVersion: v1 
metadata: 
  name: angular-service
  namespace: !{namespace}!
spec: 
  selector: 
    app: angular 
  ports: 
  - protocol: TCP 
    port: 80
    targetPort: 80
  type: LoadBalancer 
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: !{namespace}!-ingress
  namespace: !{namespace}!
spec:
  rules:
  - host: !{namespace}!.cognizant.com
    http:
      paths:
      - path: /health
        backend:
          serviceName: !{namespace}!-ingress
          servicePort: 8080
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: !{namespace}!-hpa
  namespace: !{namespace}!
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: !{namespace}!-hpa
  minReplicas: 6
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metricName: counter_active_requests
      targetAverageValue: 30
---
#apiVersion: v1
#kind: Secret
#metadata:
#  namespace: !{namespace}!
#  name: angularappsecret
#data:
#  domainpid.userid: !{namespace}!-userid
#  domainpid.password: !{namespace}!-password
---





