apiVersion: v1
kind: Namespace
metadata:
  name: !{namespace}!
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: angular-deployment
  namespace: !{namespace}! 
spec: 
  selector: 
    matchLabels: 
      app: angular 
  replicas: 2 # tells deployment to run 2 pods matching the template 
  template:
    metadata: 
      labels: 
        app: angular 
    spec: 
      containers: 
      - name: angular 
        image: cdedevopsacr.azurecr.io/angularapp:449
        #image: ramv1010/angularappdemo:latest
        ports: 
        - containerPort: 80
--- 
kind: Service 
apiVersion: v1 
metadata: 
  name: angular-service
  namespace: !{namespace}!
spec: 
  selector: 
    app: angular 
  ports: 
  - protocol: TCP 
    port: 80
    targetPort: 80
  type: LoadBalancer 