name: Migrate
on: [push]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         git clone --bare https://oauth2:$ADO_TOKEN@dev.azure.com/CDEDevOps/CDEDevOps_Assets/_git/AngularApp
         chmod +x ./migrate.sh
         ./migrate.sh
      shell: bash   
      env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
