name: Migrate
on: [push]
jobs:
  Migrate Apps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         chmod +x ./migrate.sh
         ./migrate.sh
      shell: bash   
      env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          ADO_TOKEN: ${{ secrets.ADO_TOKEN }}
